### ISSUE TITLE
Fractional Fourier Transform

### ISSUE THREAD

**Issue by roflmaostc** [SciFracX/FractionalTransforms.jl#3]
Hi!

I was wondering if you verified your `frft` implementation?
I'm trying to implement a 2D version and see major disagreements between this implementation and my code.

Best :)

Felix

**Comment by ErikQQY** [comment]
Hi there!

Looking forward to your 2D version of ```frft```!!!😄

The algorithm ```frft``` is based on https://nalag.cs.kuleuven.be/research/software/FRFT/ which is a MATLAB implementation of [Digital computation of the fractional Fourier transform](https://ieeexplore.ieee.org/document/536672).

I just fixed some problems and I think the implementation is accurate. But please note update FractionalTransform.jl to the latest version @0.1.3

**Comment by roflmaostc** [comment]
I think that fixed the major issue :D
The `frft` was somehow false for r<0.5

**Comment by ErikQQY** [comment]
Haha, yeah, there were some problems with order<0.5, but the new version is all good now. So I am closing this issue, if you have other questions, don't hesitate to ping me :D

**Comment by roflmaostc** [comment]
Hi,
As promised here is the generalization of the `FRFT`. 
It should be fairly performant.
https://github.com/bionanoimaging/FourierTools.jl/blob/fractiona_fourier_transform/src/fractional_fourier_transform.jl
